In [1]:
import numpy as np

testing script for trcreating continous motion noise stimuli from  https://www.sciencedirect.com/science/article/pii/S0165027019302237#fig0010

Create motion vector field 

In [39]:

def create_motion_vector_field(size, max_norm,min_norm):
    """
    Create a 2D array of motion vectors with random norms and phase angles.

    Parameters:
        size (tuple): Size of the 2D array (rows, columns).
        max_norm (float): Maximum value for the norm of the motion vectors.

    Returns:
        norm_array (ndarray): 2D array of norms.
        angle_array (ndarray): 2D array of phase angles (in radians).
    """
    # Randomly sample norms from a uniform distribution [0, max_norm)
    norm_array = np.random.uniform(min_norm, max_norm, size)

    # Randomly sample phase angles from a uniform distribution [0, 2π)
    angle_array = np.random.uniform(0, 360, size)

    return norm_array, angle_array

# Example usage


In [66]:
size = (16, 38,2)  # Size of the 2D array
# frames , rows , columns
max_norm = 1 
min_norm = 1  # Maximum norm value
norm_array, angle_array = create_motion_vector_field(size, max_norm,min_norm)

In [67]:
angle_array.shape

(16, 38, 2)

In [68]:
angle_array[0].shape

(38, 2)

In [70]:
angle_array[0,:,0]

257.2450839447707

In [71]:
angle_array[0]

array([[257.24508394,  35.18235129],
       [296.76150718, 318.57439516],
       [198.20022807, 332.27968778],
       [324.59245974, 289.12651463],
       [161.57044654, 308.95991243],
       [ 92.06415509, 110.77283642],
       [228.05566275, 157.97874331],
       [256.60059163,  45.7341148 ],
       [292.70350934,  14.28243478],
       [227.45104363,  30.37262226],
       [188.67566057, 180.17083582],
       [305.62014662, 135.39082655],
       [285.83222412,  27.28873376],
       [238.09949558,  12.95924408],
       [ 62.42549696, 221.21957715],
       [ 23.1338558 , 226.23515844],
       [191.36252777, 343.81208948],
       [198.08124113,  25.9164167 ],
       [124.84076015, 178.64586663],
       [213.66727493,  61.4113085 ],
       [333.84263428, 117.97723589],
       [329.89631716,  23.9941322 ],
       [  1.46145872, 298.07136861],
       [ 44.10295292, 103.51011523],
       [279.11466976, 300.0756708 ],
       [353.71035632, 343.0576819 ],
       [287.96521876, 342.08405837],
 

In [54]:
angle_array[0,:,0]

array([314.56893785,  59.67394085, 351.36160143, 160.62063691,
       355.5529367 ,  59.2304728 , 172.36366667, 164.29411048,
       181.15706183, 291.24921471, 192.06934033, 106.25673634,
        56.94654488,  74.54226273, 233.92697697, 271.03370842])

In [56]:
angle_array[0,0]

array([3.14568938e+02, 7.99632346e+01, 2.65350252e+02, 9.80621466e+01,
       3.11035609e+02, 6.93502123e+00, 3.32089140e+02, 3.31240898e-02,
       1.07075494e+02, 1.94581243e+02, 1.48419221e+02, 2.70029682e+02,
       1.00543019e+02, 2.41814732e+02, 5.14456903e+01, 2.98321242e+02,
       5.92737706e+01, 2.70616017e+02, 3.50880112e+01, 8.42482879e+01,
       1.63595898e+02, 1.13807984e+02, 2.03155845e+01, 4.74331690e+01,
       2.66833914e+02, 3.55932495e+02, 2.99085706e+02, 1.86067471e+02,
       4.07892148e+01, 9.16238959e+00, 1.84562925e+02, 2.13428367e+02,
       3.49569016e+02, 2.75511692e+02, 2.04185156e+02, 1.80639729e+02,
       2.77215982e+02, 2.29234361e+02])

In [30]:
angle_array[1,0:].shape

(16, 38)

In [50]:
angle_array[0][:,1]

array([ 79.96323464, 160.93739235, 145.87025079, 239.09574179,
       222.17565153, 190.80008575, 315.74169404, 124.98282303,
       208.12208081, 348.56256156,  72.05133137, 122.00030709,
       197.49720491, 333.18663984, 272.30193669, 357.20681382])

In [44]:
angle_array[1,0:]

array([[1.51925375e+02, 9.93335507e+01, 3.03092685e+02, 1.58930846e+01,
        2.87355871e+02, 2.01777640e+01, 1.38861516e+02, 1.48254315e+02,
        1.19159157e+01, 5.89349130e+00, 1.98326687e+02, 2.28296909e+02,
        2.18540313e+02, 2.24474538e+02, 3.29231408e+02, 9.29940886e+01,
        3.40867546e+02, 3.23477427e+02, 2.65140787e+02, 3.20532800e+02,
        2.08287746e+02, 6.54182282e+01, 2.07481154e+02, 1.14281681e+02,
        2.97631760e+02, 2.87585185e+02, 2.19206670e+02, 3.21981725e+02,
        7.54702690e+01, 2.15831277e+01, 1.69296173e+02, 2.61743847e+02,
        1.93293533e+02, 9.65326267e+00, 2.93408425e+02, 8.55616547e+01,
        2.04286460e+02, 2.89359470e+02],
       [2.68670164e+02, 1.50591957e+02, 2.80719925e+01, 2.35502831e+02,
        1.74615600e+02, 2.05922524e+02, 3.57951119e+02, 1.64745954e+02,
        3.02237816e+02, 1.37180514e+02, 1.79129437e+01, 8.24497933e+01,
        6.05431786e+01, 3.04571360e+02, 1.60328579e+02, 1.24607656e+02,
        1.82867507e+02,